### ISSUE TITLE
VM read modified on console loses buffer address of field

### ISSUE THREAD

**Issue by jphartmann** [hercules-390/hyperion#69] opened 2015-09-23 07:57 UTC
On behalf of Ivan Warren:

On 9/18/2015 2:10 PM, Ivan Warren ivan@vmfacility.fr [zHercules] wrote:
> Hello,
>
> While trying to restore a VM starter system I am running into the following issue :
>
> The 3270 read modified is behaving differently on spinhawk and hyperion.
>
> This is a bit of a trace I ran on both versions :
>
> spinhawk :
>
> 13:37:40 HHCCP048I 0010:CCW=06006B77 6000000E=>00000000 00000000 00000000 00000000 ................
> 13:37:40 HHCCP075I 0010:Stat=0C00 Count=0006 =>7D5BE211 5B609596 00000000 00000000 '$S.$-no........
> 13:37:40 HHCCP048I 0010:CCW=03000000 20000002=>000002D0 00000000 06001000 00001000 ...}............
> 13:37:40 HHCCP075I 0010:Stat=0C00 Count=0002
>
> hyperion :
>
> 13:36:48 HHC01315I 0:0010 CHAN: ccw 06006B77 6000000E
> 13:36:48 HHC01312I 0:0010 CHAN: stat 0C00, count 0009=>7D5BE295 96000000 00000000 0000     '$Sno.........
> 13:36:48 HHC01315I 0:0010 CHAN: ccw 03000000 20000002
> 13:36:48 HHC01312I 0:0010 CHAN: stat 0C00, count 0002
>
> *****
>
> spinhawk works for starter system, hyperion doesn't
>
> (note : Same emulator (Tom Brennan's VISTA 3270), same config file...)
>
> --Ivan
>
> Additional info :
> 
> 14:40:18.326041 IP (tos 0x0, ttl 128, id 25321, offset 0, flags [DF], proto TCP (6), length 50)
>     192.168.1.15.59077 > 192.168.1.38.3270: Flags [P.], cksum 0x070b (correct), seq 11:21, ack 11, win 251, length 10
>         0x0000:  4500 0032 62e9 4000 8006 1457 c0a8 010f
>         0x0010:  c0a8 0126 e6c5 0cc6 1b50 5a40 188a 523c
>         0x0020:  5018 00fb 070b 0000 7d5b e211 5b60 9596
>         0x0030:  ffef
> 
> That's a network trace of the data returned by the emulator. It does contain the entire Read Modified data (7D 5B E2 11 5B 60 95 96) - trailing FF EF is probably a Telnet Structured record delimiter.
> 
> --Ivan
>

**Comment by jphartmann** [comment] 2015-09-23 08:03
FFEF is telnet end-of-block.

Another thing might be that VM/SP uses SIO and format 0 CCWs.

**Comment by jphartmann** [comment] 2015-09-23 08:09
Are you running this test on Windows of UNIX?  If you have the "other" configuration handy, does it fail there too?  (In effect, does it fail both on Windows and UNIX?)  

Could you supply the SP5 disk image so I can try to reproduce?

**Comment by Fish-Git** [comment] 2015-09-28 18:31
@ivan-w: have you tried building with `DEBUG_LVL` set to 3 in `console.c` with an extra `packet_trace` statement insert immediately after the `recv` in function `recv_3270_data`?

**Comment by ivan-w** [comment] 2015-09-28 18:35
On 9/28/2015 8:31 PM, Fish-Git wrote:
>
> @ivan-w <https://github.com/ivan-w>: have you tried building with 
> |DEBUG_LVL| set to 3 in |console.c| with an extra |packet_trace| 
> statement insert immediately after the |recv| in function 
> |recv_3270_data|?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/hercules-390/hyperion/issues/69#issuecomment-143836001>.
>
No I haven't

But I have the CCW and TCP network traces !

That proves that somehow, some of the data is being removed.

But I will look and try to find out *WHY* such data is being removed 
(it's not like I never dwelved into hercules code)

--Ivan

**Comment by Fish-Git** [comment] 2015-09-29 01:01
@ivan-w: another very quick question: just out of curiosity, what version of Tom's Vista TN3270 terminal emulator are you using?

**Comment by ivan-w** [comment] 2015-09-29 01:37
Version 1.27

**Comment by Fish-Git** [comment] 2015-09-29 04:51
Yup. Same as me. Version 1.27. So _that_ can't be the problem.

**Comment by Fish-Git** [comment] 2015-11-17 05:01
@ivan-w: have you tried one of the pre-built Windows binaries?

* [Pre-built ready to run Windows binaries of Hercules 4.0 Hyperion courtesy of Software Development Laboratories] (http://www.softdevlabs.com/hyperion.html#prebuilt)

I'm trying to determine whether the problem also occurs on Windows or just on Linux since I am unable to reproduce it myself.

**Comment by Fish-Git** [comment] 2016-05-18 20:19
I have spoken with Ivan off-list and he has stated:

> > Is your VM/SP 5 console read-modified problem still an issue?  Does it still occur?
>
> The Read Modified issue seems to have disapeared... So either it got silently fixed or it was something I had done then that was causing the issue. Anyway, it's no longer an issue.

So I am going to go ahead and close this issue. Feel free to open it again if you determine the problem still remains.

Thanks.

**Closed by Fish-Git** 2016-05-18 20:19 UTC
Labels: BUG, Question, Researching...
