### ISSUE TITLE
Compile failed: installation Hercules (Hyprion) on MAC OS X Yosemite

### ISSUE THREAD

**Issue by ibmtimwang** [hercules-390/hyperion#73] opened 2015-10-12 17:04 UTC
Hi All

I am installation "Hercules on MAC OS X Yosemite". But I faced a problem in the step of compile of Hyperion, and the result as follows:
$ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in decNumber
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I.. -I. -DPKGDATADIR=\"/usr/local/share/hercules\" -DMODULESDIR=\"/usr/local/lib/hercules\" -DHERC_LOCALEDIR=\"/usr/local/share/locale\"  -W -Wall  -g3 -ggdb3 -O3 -march=core2 -m128bit-long-double -fomit-frame-pointer -MT decContext.lo -MD -MP -MF .deps/decContext.Tpo -c -o decContext.lo decContext.c
gcc -DHAVE_CONFIG_H -I. -I.. -I.. -I. -DPKGDATADIR=\"/usr/local/share/hercules\" -DMODULESDIR=\"/usr/local/lib/hercules\" -DHERC_LOCALEDIR=\"/usr/local/share/locale\" -W -Wall -g3 -ggdb3 -O3 -march=core2 -m128bit-long-double -fomit-frame-pointer -MT decContext.lo -MD -MP -MF .deps/decContext.Tpo -c decContext.c  -fno-common -DPIC -o .libs/decContext.o
clang: error: unknown argument: '-m128bit-long-double'
make[2]: *** [decContext.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

What I have done prior to compiling Hyperion:
1. Download xCode from Apple app store
2. Get the latest M4, automake, autoconf & libconf.
3. Find two files in hyperion directory, and then change its contents 
    In configure.ac:
      Change 
          [hc_cv_optimization_flags="$hc_cv_optimization_flags -m128bit-long-double"] )
      to 
          [hc_cv_optimization_flags="$hc_cv_optimization_flags"] )
    In hstdinc.h
         Near the top (after the comments) add: 
         #include <stddef.h>

May you help me to see what does my Mac lack of? Or I missed any step? 
Thanks for your kindly help.

**Comment by herc4mac** [comment] 2015-10-12 18:35
as a workaround use

./configure --enable-optimization="-O3 -march=native -fomit-frame-pointer" —prefix=the installation prefix

**Comment by Fish-Git** [comment] 2015-10-17 23:29
Closed as duplicate of issue #9. See there for workaround.

**Closed by Fish-Git** 2015-10-17 23:29 UTC

**Comment by krauseralf** [comment] 2015-10-17 23:31
Here is the procedure I've used to install Hyperion on OS X El Capitan:

**cd <directory with hyperion source>**
**util/bldlvlck**

**If you get an output like this one everything is fine:**
This utility will check the level of various utilities needed to build
hercules. Checking is done against versions that are KNOWN to work.
This doesn't mean a build will NOT succeed with older versions
of the utilities, but will give a hint as to what package may need
an upgrade if the build ever fails with some odd reason.


OK	autoconf requires 2.64, found 2.69

OK	automake requires 1.9, found 1.15

OK	flex requires 2.5, found 2.5.35

OK	gawk requires 3.0, found 4.1.3

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
OK	gcc requires 3, found 7.0.0

OK	grep requires 1, found 2.5.1

Apple/Darwin ==> custom version parsing!
OK	m4 requires 1.4.6, found 1.4.6

OK	make requires 3.79, found 3.81

OK	perl requires 5.6, found 5.18.2

Apple/Darwin ==> sed changed to gsed!
OK	gsed requires 3.02, found 4.2

macbook:~ rkrause$ 

**_If you need a different or newer version the tool will tell you._**

**./autogen.sh**
**CFLAGS="-O3 -D_FORTIFY_SOURCE=0" CC="gcc" ./configure --enable-optimization=no**
**make**

**_You will get some warning. But they can safely be ignored._**

**./hercules -f <path and file name of a hercules config file>**

Connect with a 3270 Emulator to hercules and ipl the system.
If everything is fine perform the last step:
**sudo make install**


That was it. For me everything was working fine and hercules is working as expected.
I didn't had any problems with this procedure. And the best of all was that I didn't had to edit any file.
I just had to install gawk and gsed.

I hope this helps!
