### ISSUE TITLE
Mac os x (Yosemite) compile error

### ISSUE THREAD

**Issue by sicaps** [hercules-390/hyperion#57] opened 2015-07-04 20:47 UTC
⇒  make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in decNumber
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I.. -I. -DPKGDATADIR=\"/usr/local/share/hercules\" -DMODULESDIR=\"/usr/local/lib/hercules\" -DHERC_LOCALEDIR=\"/usr/local/share/locale\"  -W -Wall  -g3 -ggdb3 -O3 -march=core2 -m128bit-long-double -fomit-frame-pointer -MT decContext.lo -MD -MP -MF .deps/decContext.Tpo -c -o decContext.lo decContext.c
 gcc -DHAVE_CONFIG_H -I. -I.. -I.. -I. -DPKGDATADIR=\"/usr/local/share/hercules\" -DMODULESDIR=\"/usr/local/lib/hercules\" -DHERC_LOCALEDIR=\"/usr/local/share/locale\" -W -Wall -g3 -ggdb3 -O3 -march=core2 -m128bit-long-double -fomit-frame-pointer -MT decContext.lo -MD -MP -MF .deps/decContext.Tpo -c decContext.c  -fno-common -DPIC -o .libs/decContext.o
clang: error: unknown argument: '-m128bit-long-double'
make[2]: *** [decContext.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by hackob** [comment] 2015-07-31 00:48
To bypass this error just use "--enable-optimization=no" as configure option:

$ ./configure --enable-optimization=no

**Comment by Fish-Git** [comment] 2015-09-01 21:17
Closed as duplicate of issue #9.

**Closed by Fish-Git** 2015-09-01 21:17 UTC
Labels: Duplicate
