### ISSUE TITLE
SoftFloat_types.h declares conflict with unistd.h which cause configure failure

### ISSUE THREAD

**Issue by jphartmann** [hercules-390/hyperion#204] opened 2017-03-07 12:58 UTC
The upshot is that configure terminates without diagnostic on ubuntu 14.04.  It could well be that the ubuntu file is downlevel.

In file included from /usr/data/src/hercules/x86_64/s3fh/include/softfloat_types.h:41:0,
                 from conftest.c:52:
/usr/data/src/hercules/x86_64/s3fh/include/stdint.h:40:13: error: conflicting types for 'intptr_t'
 typedef int intptr_t;
             ^
In file included from conftest.c:50:0:
/usr/include/unistd.h:267:20: note: previous declaration of 'intptr_t' was here
 typedef __intptr_t intptr_t;
                    ^
In file included from /usr/data/src/hercules/x86_64/s3fh/include/softfloat_types.h:41:0,
                 from conftest.c:52:
/usr/data/src/hercules/x86_64/s3fh/include/stdint.h:53:19: error: conflicting types for 'int64_t'
 typedef long long int64_t;
                   ^
In file included from conftest.c:21:0:
/usr/include/x86_64-linux-gnu/sys/types.h:197:1: note: previous declaration of 'int64_t' was here
 __intN_t (64, __DI__);
 ^

**Comment by srorso** [comment] 2017-03-07 14:41
Hi John:

Thanks for the complete report; give me a bit to build a 14.04 LTS (Trusty Tahr) system.  I build everything using 1Stop on 16.04 yesterday with no issues, so I join you in initially suspecting a downlevel file.  Still needs to be addressed.  

The file type of the config file created the attach issue.  Apparently Github only accepts png, gif, jpg, doxc, pptx, xlsx, txt, pdf, or zip.  (Interesting that this list seems so Microsoft-centric; no tar, odt, etc).

[config-log.txt](https://github.com/hercules-390/hyperion/files/824723/config-log.txt)

Best Regards,
Steve Orso

**Comment by srorso** [comment] 2017-03-07 19:15
Unable to reproduce on a clean build of Ubuntu 14.04.05 LTS.  On to the logs.  
```
Done 276 tests.  All OK.
srorso@ubuntu14:~/Hercules/x86_64/hyperion$ lsb_release --all
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
srorso@ubuntu14:~/Hercules/x86_64/hyperion$ 
```

**Comment by srorso** [comment] 2017-03-07 20:18
Hi John,

Would you please, via upload to this issue or pm to me, send along the following files from the SoftFloat 3a For Hercules build directory, which I believe to be `/usr/data/src/hercules/x86_64/s3fh.release` from the configure log:
```
CMakeCache.txt
cmake_install.cmake
CMakeFiles/CMakeOutput.log
```

SoftFloat 3a and SoftFloat 3a For Hercules both expect to have stdint.h and stdbool.h C99 headers.   If they are not present in the host system, CMake is set up to provide equivalent files.  In your installation, the existence of the files on the host system is not being detected, the CMake-provided files are being placed in the include directory, and these conflict with types defined in types.h provided by gcc 4.8.4.  types.h on my system matches the error line numbers from config.log.  

In the Ubuntu I just built, stdint.h can be found in:
```
/usr/lib/syslinux/com32/include/stdint.h
/usr/lib/syslinux/com32/include/bitsize/stdint.h
/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stdint.h
/usr/include/c++/4.8/tr1/stdint.h
/usr/include/stdint.h
```
And stdbool.h exists in the first, third, and fourth directories above.  

Many thanks!

Best Regards,
Steve Orso

**Comment by jphartmann** [comment] 2017-03-08 14:49
But if you want language level C99, you should specify `-std=c99` for the 4.8 series of gcc, which is what I have.  

The default for the 6.3 series is  `-std=gnu11`.  This is bound to give raise to a lot of compatibility problems.

I have these stdint plus a slew in the cross comillers, but they are well hidden:
```
1312361    4 -rw-r--r--   1 root     root          705 Jan 13  2014 /usr/lib/syslinux/com32/include/bitsize/stdint.h
1312349    4 -rw-r--r--   1 root     root         2678 Jan 13  2014 /usr/lib/syslinux/com32/include/stdint.h
4755071   24 -rw-r--r--   1 root     root        23774 Mar  5  2014 /usr/lib/llvm-3.4/lib/clang/3.4/include/stdint.h
1063781    4 -rw-r--r--   1 root     root          328 May  7  2016 /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stdint.h
1072749    8 -rw-r--r--   1 root     root         8007 May 26  2016 /usr/include/stdint.h
1217404    4 -rw-r--r--   1 root     root         1214 May  7  2016 /usr/include/c++/4.8/tr1/stdint.h
2167135    8 -rw-rw-r--   1 john     john         4114 Mar  6 14:06 /usr/data/src/hercules/x86_64/s3fh.release/stdint.h
2167251    8 -rw-r--r--   1 john     john         4114 Mar  6 14:06 /usr/data/src/hercules/x86_64/s3fh/include/stdint.h

1312347    4 -rw-r--r--   1 root     root          463 Jan 13  2014 /usr/lib/syslinux/com32/include/stdbool.h
4755070    4 -rw-r--r--   1 root     root         1730 Mar  5  2014 /usr/lib/llvm-3.4/lib/clang/3.4/include/stdbool.h
1063750    4 -rw-r--r--   1 root     root         1438 May  7  2016 /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stdbool.h
1217370    4 -rw-r--r--   1 root     root         1219 May  7  2016 /usr/include/c++/4.8/tr1/stdbool.h
2167133    4 -rw-rw-r--   1 john     john          120 Mar  6 14:06 /usr/data/src/hercules/x86_64/s3fh.release/stdbool.h
2167247    4 -rw-r--r--   1 john     john          120 Mar  6 14:06 /usr/data/src/hercules/x86_64/s3fh/include/stdbool.h

```
Requested cmake files sent separately due to github's file name extension policy.

**Comment by jphartmann** [comment] 2017-03-08 16:56
This may be a secondary issue.

I ran configure by hand and found this within a nice loud banner:
```
configure:  ERROR: Required header 'softfloat_types.h' not found. 
```
However it is here:
```
[/usr/data/src/hercules/x86_64/hyperion] find ../ -name softfloat_types.h -ls
2167241    4 -rw-r--r--   1 john     john         4045 Feb  1 16:02 ../s3fh/include/softfloat_types.h
```
Now, the banner got written to /dev/null when the commentary from configure is suppressed.  You need to write error messages to file descriptor 2.

**Comment by srorso** [comment] 2017-03-08 17:41
Hi John:

I will change configure.ac to use AC_MSG_WARN at the sections starting at lines 26, 39, and 325.  AC_MSG_WARN is not suppressed by --quiet or --silent.  Configure continues processing, which allows subsequent messages to appear up to and including AC_MSG_ERROR.  

If you would send along the updated configure log, that would be most helpful. Pm or post as is most convenient for you.

Many thanks!

Best Regards,
Steve Orso

**Comment by jphartmann** [comment] 2017-03-09 13:02
I cleaned everything out of the x86_64 directory and started afresh.  Now I get:
```
Created '../x86_64/hyperion'.
Doing autogen.sh.
configure: WARNING: softfloat_types.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: softfloat_types.h: proceeding with the compiler's result
appending configuration tag "CXX" to libtool
appending configuration tag "F77" to libtool
make  all-recursive
```
Apart from the usual shower of warnings, all looks fine and `make check` runs clean.

**Comment by srorso** [comment] 2017-03-09 13:41
Hi John:

I was reaching the conclusion that a do-over might address your issue.  But I hate receiving that kind of suggestion ("reboot your computer," "restart your phone," "power cycle your cable modem") because it sounds too much like "I don't know what's going on, so we shall start restarting things."  

Usually destroying anything of diagnostic value in the process. 

A review of the provided logs suggests that at some point CMake had cached the fact that stdint/stdbool were not available at point and declined re-tests for their presence in subsequent builds.  The issue in this case is while the answer is cached (no stdint), the process that led to that answer (the log from the run that generated the cached answer) is gone.  And so not diagnosable.  

So I may change CMakeLists.txt for SoftFloat 3a For Hercules so that it dumps the cache overboard when starting configure, which would limit cache use to during a single build and ensure that any changes in system  configuration inform S3FH CMake builds done after that change.  

That said, I would like to leave this issue open as a reminder that S3FH CMake cache use/creation needs review and likely change and to change the NOTIFY messages noted above to WARNING.   I may also elevate to "WARNING" status the message 'You may ignore the two warnings above, "accepted by the compiler, rejected by the preprocessor!'  I could not get configure to run the preprocessor with the same include libraries as the compiler when doing the header tests, hence the two warnings naming softfloat_types.h.  

I thank you for your assistance with this issue and apologize for the inconvenience you have experienced.  

Best Regards,
Steve Orso

**Comment by wrljet** [comment] 2017-03-09 13:46
Just an unwanted comment from the peanut gallery...
I hate that CMake thing.  Especially on Windows where you have to run the GUI to prepare things.

-Bill

**Comment by srorso** [comment] 2017-03-09 13:51
Hi Bill:

Your comment is most welcome.   If you are speaking of use of CMake GUI used in the currently documented build process for the Windows Support Programs for Hercules, would you open a new/separate issue for that with confirmation that it is the support programs zlib, pcre, and bzip2 you are trying to build.  

Thanks in advance!

Best Regards,
Steve Orso

**Comment by srorso** [comment] 2017-03-22 14:22
Messages changed from Notify to Warning as appropriate in configure.ac by commit 8526724.  SoftFloat 3a 

The SoftFloat-3a question regarding use or abuse of the build cache has been transferred to SoftFloat-3a For Hercules issue [#4](https://github.com/hercules-390/SoftFloat-3a/issues/4).  

The suggestion to document a non-GUI windows build process for the Windows  Support Components is transferred to Hercules issue #209.  

Closing this issue.

**Closed by srorso** 2017-03-22 14:22 UTC
Labels: BUG
