### ISSUE TITLE
Configuration scripts not testing for out-of-source build.

### ISSUE THREAD

**Issue by dasdman** [hercules-390/hyperion#176] opened 2016-12-30 04:53 UTC
<tt>bldlvlck</tt>, <tt>autogen.sh</tt>, and <tt>configure</tt>, are not ensuring that out-of-source builds are being done.

**Comment by srorso** [comment] 2016-12-30 05:27
Hi Mark:

I have code to be committed for configure.ac to test for in-source; see my prior notes on the matter.  

Autogen must run in the source directory.  

1Stop addresses autogen and configure.   

Not sure what warning is appropriate from bldlvlck, as that is run very pre-build.  I'll ponder that one.  

I'll check the SoftFloat header issue in the am. 

Best regards,
Steve Orso

+1 610 217 7050

**Comment by jphartmann** [comment] 2016-12-30 10:53
I just did a clean install using 1Stop in hyperion on Ubuntu 16.04.  I 
tried FreeBSD 11 last night.  Both pass "make check".

bldlvlch and autogen.sh run in the source directory long before 
configure.  They cannot guess how the user chooses to configure.

Autogen.sh now includes obsolete instructions on doing an out-of-source 
build.  I shall update that and also give autogen an option for 1Stop to 
omit that chatter, which is of no use when 1Stop runs the process.

Configure in the source directory fails because the softfloat library is 
not in the relative position where it ought to be.  I think Steve is 
going to move that test from the end of configure to the top, if this is 
possible; automuck is to say the least rather set in its ways (he says 
now that he knows how to get something into config.h--speak of black art!).

I think we should adopt a more restrictive stance to where things must 
be; after all, the directory structure is for us to decide.  And 
symbolic links can map any view the user wants to adopt.

But we must do that without losing track of the requirements:

*  Ability to have multiple object directories for a particular source 
directory (e.g., to support daily builds).  This is supported by 
manually performing configure from the build directory.

*  Hyperion configure must support naming a particular constituent 
package, as in --with-softloat=<name> (not =<path>).

*  Ability to have multiple parallel source directories.  Perhaps not as 
useful as above.  1Stop should support that by now as it builds the 
object directory in

	../$(uname -m)/$(basename $PWD)

I think we have the right to dictate the object directory structure as 
long as those requirements are satisfied, so I have no problem with 
forcing the directory structure of

   -  source
   -  uname -m / basename(source)

Packages that supply components (SoftFloat is no doubt the first of 
many) must have a well-known name and be a sibling of the top Hyperion 
source directory.

**Comment by srorso** [comment] 2016-12-30 14:19
Configure.ac has been updated to detect and prevent an in-source build.  Functional and regression testing done on Debian 8.6 64-bit; additional testing and feedback welcomed.  The commit for this issue also moves the SoftFloat library testing and faulure notification to much earlier in the configure script.

**Comment by srorso** [comment] 2017-01-06 22:13
Autogen.sh is supposed to run from the source directory and therefore cannot detect an in-source build.  Bldlvlck checks installed software version levels and should be run before autogen.sh, and so cannot detect an out of source build. 

Configure.ac has been updated to generate a configure script that detects and rejects attempts at an in-source build.  

Autogen.sh has been updated to provide instructions for an out-of-source build.

**Closed by srorso** 2017-01-06 22:13 UTC
