### ISSUE TITLE
Devices get ambiguous EQID 

### ISSUE THREAD

**Issue by fbi-ranger** [hercules-390/hyperion#64] opened 2015-09-16 11:44 UTC
Hercules / Hyperion on OPENsuse 13.2 
Host OS: z/VM 6.2 

BUG: the EQID for DASD is not unique. 

Description: 
Beginning with z/VM 6.2 an EQID for each unit address is generated. This EQID is constructed 
from various information from the Node Descriptor of the device or control unit (Sense data). The EQID must be unique. 

The EQID is used by zVM in various ways: 

z/VM checks the EQID in case it mounts DASD and rejects the DASD if the EQID is already used. Note: It appears that this is done only by an zVM ATTACH command. During IPL there is no problem.

Another example would be that in a z/VM SSL complex, the EQIDs are checked in order to see if the machine will find the same configuration on the destination z/VM.

Comparing the way Hercules generates the EQID for DASD with zPDT or on real iron, Hercules seems to take only the lower two bytes of a UA into account but it should take all 4 bytes for generation of a unique EQID. For OSA Hercules takes the full UA address. zPDT on the other hand uses only the last two bytes of UA plus the simulated CHPID on which the device is defined. Furthermore it uses certain values from the virtual CPU type (e.g. 2084 - z990) and other data. (Note: I would have expected 1090 or 1091. Don't know why 2084 is used on z/PDT.) 
On real iron the correct CPU type is used (e.g. 2097 z/10) . 

In the following some results from a query EQID command of z/VM are shown; 

Enhancement: 
Proposal to create a qeqid device command for Hercules to show that information independently from an OS. 

--
DASD:

Sample HERCULES

Ready; T=0.52/0.62 10:08:05
 q eqid for 5000-5001
5000: EQID = 00339000CHRCZZ000000000000000100000000000000002720
5001: EQID = 00339000CHRCZZ000000000000000100010000000000002720
Ready; T=0.01/0.01 10:08:20
 q eqid for 6200-6205
6200: EQID = 00339000CHRCZZ000000000000000100000000000000002720
6201: EQID = 00339000CHRCZZ000000000000000100010000000000002720
6202: EQID = 00339000CHRCZZ000000000000000100020000000000002720
6203: EQID = 00339000CHRCZZ000000000000000100030000000000002720
6204: EQID = 00339000CHRCZZ000000000000000100040000000000002720
6205: EQID = 00339000CHRCZZ000000000000000100050000000000002720
Ready; T=0.01/0.01 10:08:41

e.g. 5000 and 6000 gets the same EQID which should not be.
5001 and 6001 is the same.

Sample zPDT

 q eqid for 6300-6307
6300: EQID = 003390A18IBM13000000000000630000000000000000002720
6301: EQID = 003390A18IBM13000000000000630100000000000000002720
6302: EQID = 003390A18IBM13000000000000630200000000000000002720
6303: EQID = 003390A18IBM13000000000000630300000000000000002720
6304: EQID = 003390A18IBM13000000000000630400000000000000002720
6305: EQID = 003390A18IBM13000000000000630500000000000000002720
6306: EQID = 003390A18IBM13000000000000630600000000000000002720
Ready; T=0.01/0.01 10:10:20

OSA:

Sample Hercules

 query eqid for EB00-EB02
EB00: EQID = 001732001HRCZZ0000000000000000EB000000000000000000
EB01: EQID = 001732001HRCZZ0000000000000000EB010000000000000000
EB02: EQID = 001732001HRCZZ0000000000000000EB020000000000000000
Ready; T=0.01/0.01 10:18:07

Here the complete UA is taken into for the EQID.

​Sample  zPDT

 query eqid for 0F00-0F02
0F00: EQID = 001732001IBM200000208400016FFAF2000000000000000000
0F01: EQID = 001732001IBM200000208400016FFAF2010000000000000000
0F02: EQID = 001732001IBM200000208400016FFAF2020000000000000000
Ready; T=0.01/0.01 10:17:33
 query eqid for 0C00-0C02
0C00: EQID = 001732001IBM200000208400016FFAA4000000000000000000
0C01: EQID = 001732001IBM200000208400016FFAA4010000000000000000
0C02: EQID = 001732001IBM200000208400016FFAA4020000000000000000
Ready; T=0.01/0.01 10:21:17

​On zPDT the are different characteristics A4 and F2 are the simulated channel paths for the OSA addresses.

**Comment by Fish-Git2** [comment] 2015-09-16 18:43
FYI: issue #16 is a duplicate of this one, but since github does not support merging two separate issues together into just one issue, I am keeping both github issues separate from one another since the other issue (#16) contains additional information.

When either github issue is closed the responsible party should take care to also close the other github issue too.

**Comment by Fish-Git2** [comment] 2015-09-16 19:12
dasdman reports:

> I've got the complete fix for this mixed in with the rest of the DASD
> update. Key problem is that it requires CHANBLOK, CUBLOK and functions
> previously removed (I don’t have the complete list at the moment). Fix
> also includes CUID specification on the DASD statement.

I don't understand why such "missing functions" problems occur in the first place.

Shouldn't all of the functions that your new code requires be part of your new code? Why would you (or whoever/anyone) add new functions which existing code never uses (will never use)? Shouldn't those new functions that your new code requires be added **_at the the same time as your new code?_**

Why add one part of your new code months or years ahead of time when it won't ever be used/needed until you finally commit your new code months/years later? Why the two widely-separated-in-time commits instead of one _complete_ commit that contains everything needed (which makes more sense)?

Regardless however, I will go ahead and commit the "quick fix" for this issue in the mean time while you try to locate your missing functions. Please let me know if there is anything I can do to help you in that regard. I very much look forward to seeing this new code of yours, dasdman. :)

**Comment by Fish-Git** [comment] 2015-09-18 04:05
> Enhancement:
> Proposal to create a qeqid device command for Hercules to show that information independently from an OS.

I have changed our existing `qd` command (which was previously called "query dasd") to now work for _any_ device:

    HHC01603I help q*
    HHC01603I
    HHC01602I Command      Description
    HHC01602I -------      -----------------------------------------------
    HHC01602I qcpuid      *Display cpuid
    HHC01602I qd          *Query device information
    HHC01602I qeth        *Enable/Disable QETH debugging
    HHC01602I qpfkeys      Display the current PF Key settings
    HHC01602I qpid         Display Process ID of Hercules
    HHC01602I qports       Display TCP/IP ports in use
    HHC01602I qproc        Display processors type and utilization
    HHC01602I qstor        Display main and expanded storage values
    HHC01602I quit        *Terminate the emulator
    HHC01603I
    HHC01610I  (*)  Enter "help <command>" for more info.
    HHC01603I

    HHC01603I help qd
    HHC01603I
    HHC01602I Command      Description
    HHC01602I -------      -------------------------------------------------------
    HHC01602I qd          *Query device information
    HHC01603I
    HHC01603I Format: "qd [devnum(s)] | [devclass]" where 'devnum(s)' is either
    HHC01603I a single device number or a multiple device number specification
    HHC01603I in the same format as used for configuration file device statements,
    HHC01603I and 'devclass' is either CHAN, CON, CTCA, DASD, DSP, FCP, LINE, OSA,
    HHC01603I PCH, PRT, RDR or TAPE. When no argument is given all devices are shown.
    HHC01603I

    HHC01603I qd a80
    HHC02280I 0:0A80 SNSID 00  FF3990EC 33900A00 40FA0100 41270004
    HHC02280I              10  423E0040
    HHC02280I 0:0A80 RDC   00  3990EC33 900AD000 10102024 0D0B000F
    HHC02280I              10  E000E5A2 05940222 13090674 00000000
    HHC02280I              20  00000000 00000000 24240602 DFEE0001
    HHC02280I              30  0677080F 003F0000 00FF0000 00000000
    HHC02280I 0:0A80 RCD   00  C4010100 4040F3F3 F9F0F0F0 C1C8D9C3 |D...  339000AHRC|
    HHC02280I              10  E9E9F0F0 F0F0F0F0 F0F0F0F0 F0F10080 |ZZ000000000001..|
    HHC02280I              20  C4000000 4040F3F3 F9F0F0F0 C1C8D9C3 |D...  339000AHRC|
    HHC02280I              30  E9E9F0F0 F0F0F0F0 F0F0F0F0 F0F10000 |ZZ000000000001..|
    HHC02280I              40  D4020000 4040F3F9 F9F0F0C5 C3C8D9C3 |M...  39900ECHRC|
    HHC02280I              50  E9E9F0F0 F0F0F0F0 F0F0F0F0 F0F1000A |ZZ000000000001..|
    HHC02280I              60  F0000001 4040F3F9 F9F04040 40C8D9C3 |0...  3990   HRC|
    HHC02280I              70  E9E9F0F0 F0F0F0F0 F0F0F0F0 F0F10000 |ZZ000000000001..|
    HHC02280I              80  00000000 00000000 00000000 00000000 |................|
    HHC02280I              90  00000000 00000000 00000000 00000000 |................|
    HHC02280I              A0  00000000 00000000 00000000 00000000 |................|
    HHC02280I              B0  00000000 00000000 00000000 00000000 |................|
    HHC02280I              C0  00000000 00000000 00000000 00000000 |................|
    HHC02280I              D0  00000000 00000000 00000000 00000000 |................|
    HHC02280I              E0  80000004 00001E00 0A808080 80800400 |................|
    HHC02280I              F0  00808080 00000000 00000000 00000000 |................|
    HHC02280I 0:0A80 SNSS  00  00801F00 00000000 00000000 00000000
    HHC02280I              10  00000000 00000000 00000000 00000000
    HHC02280I              20  00000000 00000A80

    HHC01603I qd tape
    HHC02280I 0:0580 SNSID 00  FF349050 349050
    HHC02280I 0:0580 RDC   00  34905034 90500000 02C08080 00000000
    HHC02280I              10  00000000 00000000 34905034 90500000
    HHC02280I              20  00000000 00000000 42810000 00000000
    HHC02280I              30  00000000 00000000 00000000 00000000
    HHC02280I 0:0580 RCD   00  CC010200 F0F0F3F4 F9F0C3F1 F0C8D9C3 |....003490C10HRC|
    HHC02280I              10  E9E9F0F0 F0F0F0F0 F0F0F0F0 F0F00000 |ZZ000000000000..|
    HHC02280I              20  C4020000 F0F0F3F4 F9F0C3F1 F0C8D9C3 |D...003490C10HRC|
    HHC02280I              30  E9E9F0F0 F0F0F0F0 F0F0F0F0 F0F00000 |ZZ000000000000..|
    HHC02280I              40  00000000 00000000 00000000 00000000 |................|
    HHC02280I              50  00000000 00000000 00000000 00000000 |................|
    HHC02280I              60  EC000000 F0F0F3F4 F9F0C3F1 F0C8D9C3 |....003490C10HRC|
    HHC02280I              70  E9E9F0F0 F0F0F0F0 F0F0F0F0 F0F00000 |ZZ000000000000..|
    HHC02280I              80  80800080 00000000 00000000 00000000 |................|
    HHC02280I              90  00000000 00000000 00000000 00000000 |................|
    HHC02280I 0:0590 SNSID 00  FF359050 359010
    HHC02280I 0:0590 RDC   00  35905035 90100000 4EC48080 00000000
    HHC02280I              10  00000000 00000000 35905035 90100000
    HHC02280I              20  00000000 00000000 46830000 00000000
    HHC02280I              30  00000000 00000000 00000000 00000000
    HHC02280I 0:0590 RCD   00  CC010200 F0F0F3F5 F9F0C2F1 C1C8D9C3 |....003590B1AHRC|
    HHC02280I              10  E9E9F0F0 F0F0F0F0 F0F0F0F0 F0F00000 |ZZ000000000000..|
    HHC02280I              20  C4020000 F0F0F3F5 F9F0C1F5 F0C8D9C3 |D...003590A50HRC|
    HHC02280I              30  E9E9F0F0 F0F0F0F0 F0F0F0F0 F0F00000 |ZZ000000000000..|
    HHC02280I              40  00000000 00000000 00000000 00000000 |................|
    HHC02280I              50  00000000 00000000 00000000 00000000 |................|
    HHC02280I              60  EC000000 F0F0F3F5 F9F0C2F1 C1C8D9C3 |....003590B1AHRC|
    HHC02280I              70  E9E9F0F0 F0F0F0F0 F0F0F0F0 F0F00000 |ZZ000000000000..|
    HHC02280I              80  80800080 00000000 00000000 00000000 |................|
    HHC02280I              90  00000000 00000000 00000000 00000000 |................|

    HHC01603I qd 700-701,703
    HHC02280I 0:0700 SNSID 00  FF32741D 327802
    HHC02280I 0:0701 SNSID 00  FF32741D 327802
    HHC02280I 0:0703 SNSID 00  FF32741D 327802

The information the Hercules `qd` command displays is the very same information that z/VM's "query eqid" command displays, _however_, as you can see, Hercules displays it in a different format. (Hercules displays the raw information whereas z/VM formats it in a more compact (condensed) format.)

I hope that this is good enough to satisfy your enhancement request since I hope you would also agree that it is not worthwhile to spend yet even more valuable time and effort to create a completely separate command (or to modify the existing one) simply to display the exact same information but in a different format.

**Comment by fbi-ranger** [comment] 2015-09-18 04:25
Hi Fish,

Great! I totally agree. Thanks for your effort.

Kind regards,
Florian

**Comment by Fish-Git** [comment] 2015-09-19 02:42
While there may still be work left to do in this area, for now, the immediate problem has been resolved.

So....

Am closing this issue.

**Closed by Fish-Git** 2015-09-19 02:42 UTC
Labels: BUG, Duplicate, Fix being tested..., In progress...
