### ISSUE TITLE
RISBGN instruction?

### ISSUE THREAD

**Issue by Sardonimous** [hercules-390/hyperion#162] opened 2016-10-21 21:54 UTC
Getting the following booting ubuntu 16.10

HHC00801I Processor CP00: Operation exception code 0001  ilc 6
HHC02324I PSW=0705000180000000 000003FF9DC0B666 INST=EC1220211E59 ????? ,                      ?

This appears to be an RISBGN instruction (ECxxxxxxxx59) , similar to RISBG but without setting the cc and is part of the Miscellaneous Instruction Extensions Facility feature introduced with the zEC12.  

I don't see this in the general3.c nor opcode.c

**Comment by Sardonimous** [comment] 2016-10-21 23:01
Note, spinhawk has this support.

**Comment by Fish-Git** [comment] 2016-10-22 00:58
This is a duplicate of issue #20.

**Closed by Fish-Git** 2016-10-22 00:58 UTC
Labels: Duplicate
