### ISSUE TITLE
Unusual persistent QETH (OSA QDIO) error

### ISSUE THREAD

**Issue by fbi-ranger** [hercules-390/hyperion#63] opened 2015-09-16 08:29 UTC
Host environment: HERCULES / Hyperion 4.0 on openSUSE 13.2.

Guest O/S: z/VM 6.2 (RSU 1302)

The z/VM TCPIP stack is properly configured and known to work. (Stack works fine with LCS devices.)

When trying to define an OSA QDIO virtual switch however, an error occurs (unusual channel status).

z/VM then attempts error recovery by detaching and then reattaching the devices, which leads to the very same error again. This attach, error, detach cycle will then continue until a `set vswitch name disconn` z/VM command is given to cause it to stop.

Attached is a Hercules CCW trace spanning several error recovery cycles of the three QETH devices involved as well as the console log of the z/VM "DTCVSW2" userid who is responsible for managing the   switch's stack.

Please let me know if you need any further information to properly debug this issue.

Thank you.

Attached files: [DTCVSW2.CONS.LOG, herc400.log](https://gist.github.com/Fish-Git/bf70e4306b5a2a83ce1a)

**Comment by Fish-Git** [comment] 2015-09-18 01:57
This is an interesting bug!

Looking at the DTCVSW2 log we can see z/VM reporting a channel error:

    08:34:55 DTCQDI001I QDIO device VMINTR10600DEV device number 0600:
    08:34:55 DTCPRI461I      Keys: E0, CcwAddress: 01F09558
    08:34:55 DTCPRI462I    Status bits: C0, SCFA: 4017
    08:34:55 DTCPRI463I    Unit Status: 00, Channel Status: 20
    08:34:55 DTCPRI464I    Byte Count:            0
    08:34:55 DTCPRI470I    Subchannel Logout: 00800000

Channel status 20 is a Channel Program Check (`CSW_PROGC`). The hercules CCW trace log shows the same error, but provides a bit more of a clue as to the cause:

    14:34:55 HHC01315I 0:EB00 CHAN: ccw 1F600001 8FFFFF02=>00                                  .
    14:34:55 HHC01312I 0:EB00 CHAN: stat 0020, count 0000
    14:34:55 HHC01317I 0:EB00 CHAN: scsw E0C04017, stat 0020, count 0000, ccw 7FF9BF40
    14:34:55 HHC01318I 0:EB00 CHAN: test I/O: cc=0

The two clues provided are: 1) the CCW opcode (`1F` = `OSA_AQ` = Activate Queues), and 2) a CCW I/O buffer address of `8FFFFF02` (which is well above the 2GB line).

Investigating further under the working presumption that it might likely be the CCW's I/O buffer address that caused the channel to throw the CSW_PROGC, leads us directly to the following code segment in channel.c's "execute_ccw_chain" function:

          /* Update current CCW opcode, unless data chaining */
          if (!(skip_ccws ||
                (dev->chained & CCW_FLAGS_CD)))
          {
              dev->prevcode = dev->code;
              dev->code = opcode;

              /* Allow the device handler to determine whether this is
                 an immediate CCW (i.e. CONTROL with no data transfer) */
              dev->is_immed = IS_CCW_IMMEDIATE(dev, opcode);

              /*-- TBD ------------------------------------------------*/
              /*                                                       */
              /*   Initiation and check of opcode with control unit    */
              /*   belongs here.                                       */
              /*                                                       */
              /*-------------------------------------------------------*/

          }

          /* If immediate, chain data and address are ignored */
          if (dev->is_immed)
          {
              flags &= ~CCW_FLAGS_CD;
              dev->chained &= ~CCW_FLAGS_CD;
              addr = 0;
          }

          /* Channel program check if CCW refers to invalid storage    */
          /* SA22-7201-05:                                             */
          /*  p. 15-24, Data Address                                   */
          /*  p. 15-25, Count                                          */
          /*  pp. 15-25 -- 15-27, Designation of Storage Area          */
          if ((count &&
               (!(flags & CCW_FLAGS_SKIP)) &&
               (((flags & CCW_FLAGS_IDA)   &&
                 ((addr & 0x03) ||
                  CHADDRCHK(addr, dev)))                      ||
        #if defined(FEATURE_MIDAW)
                ((flags & CCW_FLAGS_MIDAW) &&
                 ((addr & 0x0F) ||
                  CHADDRCHK(addr, dev)))                      ||
        #endif /*defined(FEATURE_MIDAW)*/
                (!(flags & (CCW_FLAGS_IDA | CCW_FLAGS_MIDAW))     &&
                 ((ccwfmt == 0 &&
                   ((addr & ~0x00FFFFFF)                      ||
                    ((addr + (count - 1)) & ~0x00FFFFFF)      ||
                    CHADDRCHK((addr + (count - 1)), dev)))    ||
        #if defined(FEATURE_CHANNEL_SUBSYSTEM)
                  (ccwfmt == 1 &&
                   ((addr & ~0x7FFFFFFF)                      ||
                    ((addr + count - 1) & ~0x7FFFFFFF)        ||
                    CHADDRCHK((addr + (count - 1)), dev)))        ||
        #endif /*defined(FEATURE_CHANNEL_SUBSYSTEM)*/
                   CHADDRCHK(addr, dev)))))
        #if defined(FEATURE_CHANNEL_SUBSYSTEM)
           || (!count &&
               (ccwfmt == 1 && (flags & CCW_FLAGS_CD)))
        #endif /*defined(FEATURE_CHANNEL_SUBSYSTEM)*/
              )
          {
              chanstat = CSW_PROGC;
              if (prefetch.seq)
                  goto prefetch;
              goto breakchain;
          }

Notice two things: 1) the call to `IS_CCW_IMMEDIATE` to determine whether the CCW opcode is an "immediate" command or not, and 2) the test to check whether the CCW's buffer address is outside (beyond) the architectural limit of 2GB: `((addr & ~0x7FFFFFFF) || ((addr + count - 1) & ~0x7FFFFFFF)`.

So now the questions become: 1) Why is `IS_CCW_IMMEDIATE` returning "false" for the Activate Queues (`OSA_AQ` = `1F`) CCW command/opcode?, and 2) Is this correct or is this wrong?

Looking at the code in qeth.c to see what the "Activate Queues" CCW opcode actually does (to determine whether or not the CCW I/O buffer address is used/needed or not) reveals that the Activate Queues command in fact does **_not_** reference the CCW's I/O buffer _at all_, indicating that the Activate Queues command is indeed an "immediate" command whose buffer address is never used.

Which leads to the obvious conclusion that `IS_CCW_IMMEDIATE` is in fact returning "false" when it should obviously be returning "true", which we can quickly prove as indeed being the case by a simple examination of qeth.c's `qeth_immed_commands` table:

    static BYTE qeth_immed_commands [256] =
    {
    /* 0 1 2 3 4 5 6 7 8 9 A B C D E F */
       0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0, /* 00 */
       0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, /* 10 */
       0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, /* 20 */
       0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, /* 30 */
       0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, /* 40 */
       0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, /* 50 */
       0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, /* 60 */
       0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, /* 70 */
       0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, /* 80 */
       0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, /* 90 */
       0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, /* A0 */
       0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, /* B0 */
       0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, /* C0 */
       0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, /* D0 */
       0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, /* E0 */
       0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0  /* F0 */
    };

Ah-HA! There's the bug! The table entry for the `1F` opcode is zero! The hercules QETH device driver (qeth.c) is basically _lying_ to the channel code in channel.c by erroneously telling it Activate Queues is not an immediate command when in fact it actually is.

The fix for this bug is a simple _one **bit**_ change to qeth.c's `qeth_immed_commands` table:

    --- hercules-1/qeth.c	2015-09-17 06:36:32.193208000 -0700
    +++ hercules-0/qeth.c	2015-09-17 18:45:57.816809200 -0700
    @@ -268,7 +268,7 @@
     {
     /* 0 1 2 3 4 5 6 7 8 9 A B C D E F */
        0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0, /* 00 */
    -   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, /* 10 */
    +   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1, /* 10 */
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, /* 20 */
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, /* 30 */
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, /* 40 */

This should cause channel.c to pass its invalid storage reference check and prevent the Channel Program Check which is occurring.

I will commit this fix shortly after I fix some accidental compile errors I accidentally introduced in my previous commit first.

Hang loose, Florian!  The fix is coming. :)

**Closed** 2015-09-18 03:31 UTC
Labels: BUG, In progress...
